version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/timelance
      - SECRET_KEY=mysecretkey
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - internal-network


  mongo:
    image: mongo:4.4
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: mongoroot
      # MONGO_INITDB_ROOT_PASSWORD: mongorootpassword
    volumes:
      - ~/mongo-data:/data/db
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - internal-network
    security_opt:
      - no-new-privileges:true
    command: ["mongod", "--config", "/etc/mongod.conf"]

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - REACT_APP_BACKEND_HOST=http://localhost:5000

volumes:
  mongo-data:
    driver: local

networks:
  internal-network:
    driver: bridge
